<a href="https://colab.research.google.com/github/patrasachin/Machine_Learning/blob/main/Multivalue_LinearRegressiion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import Librarie

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [ ]:
#Dataset
url="https://raw.githubusercontent.com/apratim777/apratim777/refs/heads/master/homeprices1.csv"
df=pd.read_csv(url)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
#Find the median for the missing value in bedrooms

df.bedrooms.median()

4.0

In [ ]:
#Fill the missing value by median

df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
# Separate input features (x) by removing the target column 'price'

x = df.drop('price', axis='columns')
x

   area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [ ]:
## Drop the feature columns 'area', 'bedrooms', and 'age' to keep only the target column(s) in y

y = df.drop(['area', 'bedrooms', 'age'], axis='columns')
y

    price
0  550000
1  565000
2  610000
3  595000
4  760000
5  810000

In [ ]:
# Create an instance of the Linear Regression model

reg=LinearRegression()

In [ ]:
# Train (fit) the Linear Regression model using input feature(s) x and target variable y

reg.fit(x,y)

LinearRegression()

In [ ]:
#Predict the output

reg.predict([[3200,4,18]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[615307.4140366]])

In [ ]:
#find the coefficient(slope)

reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [ ]:
#find intercept
reg.intercept_

array([221323.0018654])

In [ ]:
#Check the prediction is right or wrong

 (112.06244194*3200)+(23388.88007794*4)+(-3231.71790863*18)+221323.0018654

615307.4140298201